"""Export OpenMDAO script from jupyter notebook."""

import os

from traitlets import default
from traitlets.config import Config

from nbconvert.preprocessors.execute import ExecutePreprocessor
from nbconvert.exporters.python import PythonExporter

# key for widget state in notebook
widget_key = 'application/vnd.jupyter.widget-view+json'

# values that should not be quoted
unquoted = ['True', 'False', 'None']


class OMPreprocessor(ExecutePreprocessor):
    # widget types for which we will generate code
    widget_types = [
        'DropdownModel',
        'FloattTextModel',
        'IntTextModel',
        'SelectMultipleModel',
        'TextareaModel',
    ]

    # list of commands generated by processing widgets
    widget_code = []

    def process_widget(self, widget, obj_name):
        """
        Generate Python code to reflect widget state.

        Python commands are added to the `widget_code` class attribute.

        Parameters
        ----------
        widget : dict
            Metadata for widget.
        obj_name: str
            The name of the object to which the widget properties are to be applied.
        """
        wtype = widget['_model_name']
        if wtype in self.widget_types and not widget['disabled']:
            desc = widget['description']

            if wtype in ['FloatTestModel', 'IntTextModel']:
                cmd = f"{obj_name}.{desc} = {widget['value']}"

            elif wtype == 'DropdownModel':
                val = widget['_options_labels'][widget['index']]
                if val not in unquoted and not val.isnumeric():
                    val = f"'{val}'"
                cmd = f"{obj_name}.{desc} = {val}"

            elif wtype == 'SelectMultipleModel':
                values = [widget['_options_labels'][i] for i in widget['index']]
                cmd = f"{obj_name}.{desc} = {values}"

            elif wtype == 'TextareaModel':
                lines = widget['value'].split('\n') if widget['value'] else []
                cmd = f"{obj_name}.{desc} = {lines}"

            self.widget_code.append(cmd)

        if 'children' in widget:
            for child in widget['children']:
                child_id = child.replace("IPY_MODEL_", "")
                self.process_widget(self.widget_state[child_id], obj_name)

    def preprocess(self, nb, resources=None, km=None):
        """
        Preprocess notebook executing each code cell.

        The input argument *nb* is modified in-place.

        Parameters
        ----------
        nb : NotebookNode
            Notebook being executed.
        resources : dictionary (optional)
            Additional resources used in the conversion process.
        km: KernelManager (optional)
            Optional kernel manager.

        Returns
        -------
        nb : NotebookNode
            The executed notebook.
        resources : dictionary
            Additional resources used in the conversion process.
        """
        super().preprocess(nb, resources, km)

        for cell in nb.cells:
            if cell['cell_type'] == 'code':

                meta = cell['metadata']
                if 'tags' in meta:
                    tags = meta['tags']
                    if 'remove-input' in tags or 'active-ipynb' in tags:
                        cell['source'] = ''
                        continue

                if 'outputs' in cell:
                    for outp in cell['outputs']:
                        if 'data' in outp and widget_key in outp['data']:
                            # the object which generated the widget will be the last line
                            # of the cell source (otherwise the widget would not display)
                            obj_name = cell['source'].rstrip().split('\n')[-1]
                            model_id = outp['data'][widget_key]['model_id']
                            self.process_widget(self.widget_state[model_id], obj_name)

                if self.widget_code:
                    cell['source'] += '\n'+'\n'.join(self.widget_code)
                    self.widget_code = []

        return nb, resources


class OMExporter(PythonExporter):
    """
    Exports an OpenMDAO code file.
    Note that the file produced will have a shebang of '#!/usr/bin/env python'
    regardless of the actual python version used in the notebook.
    """
    def __init__(self, config=None, **kw):
        """
        Public constructor

        Parameters
        ----------
        config : ``traitlets.config.Config``
            User configuration instance.
        `**kw`
            Additional keyword arguments passed to parent __init__
        """
        self.preprocessors.append(OMPreprocessor())

        super().__init__(config=None, **kw)

    @property
    def default_config(self):
        c = Config({
            "ExecutePreprocessor": {"enabled": False},
            "ClearOutputPreprocessor": {"enabled": False},
            "TemplateExporter": {"exclude_output_prompt": True, "exclude_input_prompt": True}
        })
        c.merge(super().default_config)
        return c


def _jupyter_bundlerextension_paths():
    """OpenMDAO bundler extension"""
    return [{
        'name': 'openmdao_bundler',                       # unique bundler name
        'label': 'OpenMDAO Script',                       # human-readable menu item label
        'module_name': 'openmdao.utils.notebook_export',  # module containing bundle()
        'group': 'download'                               # group under 'deploy' or 'download' menu
    }]


def bundle(handler, model):
    """Transform, convert, bundle, etc. the notebook referenced by the given
    model.

    Then issue a Tornado web response using the `handler` to redirect
    the user's browser, download a file, show a HTML page, etc. This function
    must finish the handler response before returning either explicitly or by
    raising an exception.

    Parameters
    ----------
    handler : tornado.web.RequestHandler
        Handler that serviced the bundle request
    model : dict
        Notebook model from the configured ContentManager
    """
    from nbconvert.nbconvertapp import NbConvertApp

    class OMExporterApp(NbConvertApp):
        @default("export_format")
        def default_export_format(self):
            return "openmdao"

    ipynb_file = model['path']
    py_file = ipynb_file.replace('.ipynb', '.py')

    try:
        os.remove(py_file)
        print("Existing file deleted.")
    except Exception as err:
        print(err)

    omx = OMExporterApp()
    omx.initialize()
    omx.notebooks = [model['path']]
    omx.convert_notebooks()
    handler.finish(f"OpenMDAO script saved to {os.getcwd()}/{py_file}.")
